Laba1/Components/MenuViewComponent.cs
using Laba1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laba1.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
            new MenuItem{ Controller="Product", Action="Index", Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
        };
        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                var _matchController = controller?.Equals(item.Controller) ?? false;
                var _matchArea = area?.Equals(item.Area) ?? false;
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

Laba1/Views/Shared/Components/CartViewComponent.cs
using Laba1.Extensions;
using Laba1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laba1.Views.Shared.Components
{
	public class CartViewComponent : ViewComponent
	{
		private Cart _cart;
		public CartViewComponent(Cart cart)
		{
			_cart = cart;
		}
		public IViewComponentResult Invoke()
		{
			var cart = HttpContext.Session.Get<Cart>("cart");
			return View(cart);
		}
	}
}

Laba1/Views/Shared/Index.cshtml
@model ListViewModel<Dish>
@{
    ViewData["Title"] = "Меню";
    var categories = ViewData["Groups"] as IEnumerable<DishGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];

    var text = currentGroup != 0 ? categories.FirstOrDefault(g => g.DishGroupId == currentGroup)?.GroupName : "Все";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-2">
        <div class="btn-group mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Product"
               role="button"
               id="dropdownMenuLink"
               data-bs-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false">
                @text
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-action="Index" asp-controller="Product">Все</a></li>

                @foreach (var item in categories)
                {
                    <li>
                        <a class="dropdown-item"
                           asp-action="Index"
                           asp-controller="Product"
                           asp-route-group="@item.DishGroupId"
                           asp-route-pageNo="1">
                            @item.GroupName
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="col-10" justify-content-start>
        <div class="card-group" id="list">
            <partial name="_ListPartial" model="@Model" />
        </div>
        <pager page-current="@Model.CurrentPage"
               page-total="@Model.TotalPages"
               action="Index"
               controller="Product"
               group-id="@currentGroup"></pager>
    </div>

</div>

Laba1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laba1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laba1.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<div class="container ">
				<!-- меню сайта -->
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">WebLabs1-9</a>
                @* <div class="navbar-nav"> *@
                    @await Component.InvokeAsync("Menu")
                @* </div> *@
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
			</div>
		</nav> 
        
    </header>

    <main class="container mt-3">
        @RenderBody()
    </main>

    <footer class="navbar fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Laba1/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using Laba1.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager
<!-- Корзина -->
@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
            @* <img src=" @Url.Action("GetAvatar","Image")" width="30" alt="User" class="rounded bg-light" /> *@
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
            <li>
                <a class="dropdown-item" href="#">
                    <img img-action="GetAvatar"
                         img-controller="Image"
                         width="30" alt="User"
                         class="rounded bg-light" />

                    @* <img src=" @Url.Action("GetAvatar","Image")" width="50" alt="User" class="rounded" /> *@
                    @User.Identity.Name
                </a>
            </li>
            <li class="dropdown-divider"></li>
            <li><a class="dropdown-item" asp-action="Index" asp-controller="Cart">Мои товары</a></li>
            <li>
                <form asp-area="Identity"
                      asp-page="/Account/Logout"
                      asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                    <input type="submit"
                           value="Log off"
                           class="dropdown-item" />
                </form>
            </li>
        </ul>
    </div>
}
else
{
    <ul class="nav navbar-nav ms-auto">
		<li>
			<a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Login">Войти</a>
		</li>
		<li>
			<a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Register">Зарегистрироваться</a>
		</li>
	</ul>
}